export const FILTER = "FILTER";
export const ALL_ITEMS = "ALL_ITEMS";
export const ALL_ITEMS_ADMIN = "ALL_ITEMS_ADMIN";
export const GET_PRODUCT = "GET_PRODUCT";
export const ALL_CATEGORY = "ALL_CATEGORY";
export const ALL_CATEGORY_ADMIN = "ALL_CATEGORY_ADMIN";
export const ALL_SUBCATEGORY_ADMIN = "ALL_SUBCATEGORY_ADMIN";
export const ALL_SUBCATEGORY = "ALL_SUBCATEGORY";
export const ALL_USERS = "ALL_USERS";
export const SET_PAGINADO= "SET_PAGINADO";
export const SET_CATEGORY= "SET_CATEGORY";
export const SET_SUBCATEGORY= "SET_SUBCATEGORY";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const EDITAR_PRODUCTO = "EDITAR_PRODUCTO";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const DISABLE_CATEGORY = "DISABLE_CATEGORY";
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";
export const DISABLE_SUBCATEGORY = "DISABLE_SUBCATEGORY";

export const ADD_USER = "ADD_USER"
export const CHECK_ROLE = "CHECK_ROLE"

export const GET_USER_ADDRESS = "GET_USER_ADDRESS";
export const POST_USER_ADDRESS = "POST_USER_ADDRESS"
export const UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS"
